spring.application.name=spendwise-backend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spendwise}
spring.datasource.username=${DB_USERNAME:spendwise}
spring.datasource.password=${DB_PASSWORD:spendwise_dev_password}

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

jwt.secret=${JWT_SECRET}